name: Frontend Build

on:
  push:
    branches:
      - shouye

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v5

      - name: 安装 Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - name: 安装依赖
        run: npm ci

      - name: 构建前端
        run: npm run build